# -*- coding: utf-8 -*-
"""SmartSenseA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YeJpo2sCJmzlPu28pSlbrH8sAA0NtBlB
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline
from sklearn.metrics import accuracy_score

data = pd.read_csv('/HRA.csv', delimiter=',')

data.head() #data given

data.describe() # calculating the statisitics

data.info()

data.isnull().values.any() # checking is there any null  values

data[data['left']==1].shape[0]    # Number of employees that left

data[data['left']==0].shape[0]    # Number of employees that are still working there

group_a = data[data['left']==1].mean()    # Divide left employees in different sales
print(group_a)

group_b = data[data['left'] == 0].mean() # Divide working employees and those who do not left in different sales
print(group_b)

sns.set(style="white")

# Compute the correlation matrix
corr = data.corr()

# Generate a mask for the upper triangle
mask = np.zeros_like(corr, dtype=np.bool)
mask[np.triu_indices_from(mask)] = True

# Set up the matplotlib figure
f, ax = plt.subplots(figsize=(5, 4))

# Generate a custom diverging colormap
cmap = sns.diverging_palette(10, 500, as_cmap=True)

# Draw the heatmap with the mask and correct aspect ratio
sns.heatmap(corr, mask=mask, cmap=cmap, vmax=.5,
            square=True, xticklabels=True, yticklabels=True,
            linewidths=.5, cbar_kws={"shrink": .5}, ax=ax)

"""#Conclusion

#### As we can see from the above map, we can say that the region with red(left,satisfaction_level), shows that is the reason why most of the employees left. The colour of red represents -ve value in the correlation matrix, which means people have less satisfaction level, and also other areas like work accident. These are the areas were dark in "left" column. So, satisfactional_level, and work_accident are the main reasons for best and most experienced employees leave prematurely.
"""